In [1]:
import numpy as np
a = np.array([[1,2,4],
              [2,4,5]])
print(a)

[[1 2 4]
 [2 4 5]]


In [3]:
from skimage import io
photo = io.imread(r'/Users/sudeepdemishra/Documents/Python-College/Forking/PythonResources/test.png')

In [6]:
import matplotlib.pyplot as plt
print(np.sum(photo))

1759482199


In [ ]:
print(np.prod(photo)) 

0


In [8]:
print(np.mean(photo))

114.49404501304575


In [9]:
print(np.std(photo))

84.82388923686206


In [10]:
print(np.var(photo))

7195.092185267442


In [11]:
print(np.min(photo))

0


In [13]:
print(np.max(photo))

255


In [ ]:
print(np.argmin(photo)) # index value of min

463820


In [15]:
print(np.argmax(photo))

3


In [16]:
newArray = np.array([[1,2,3],
                     [3,5,6],
                     [1,4,5]])
print(np.min(newArray))

1


In [18]:
print(np.max(newArray))
newArray<3

6


array([[ True,  True, False],
       [False, False, False],
       [ True, False, False]])

In [21]:
print(newArray[newArray<3])

[1 2 1]


In [22]:
newArray[newArray<3]

array([1, 2, 1])

In [23]:
arr1 = np.array([1,3,4,5])
arr2 = np.array([3,4,6,7])
arr1 + arr2

array([ 4,  7, 10, 12])

In [24]:
z = np.power(arr1, 3)
z

array([  1,  27,  64, 125])

In [27]:
z = np.append(z, [30], axis=0)
z

array([  1,  27,  64, 125,  30,  30])

In [ ]:
arr1 @ arr2 # dot(.) product

np.int64(74)

In [31]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
arr1 = np.arange(10)
arr2 = np.arange(12).reshape(2,6)
print(arr2)
arr3 = np.arange(8).reshape(2,2,2) # 2 blocks of 2 row and 2 column
print(arr3)
np.ndim(arr1)
arr3.size
arr3

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [37]:
arr = np.array([1,2,3], dtype=float)
print(arr)

[1. 2. 3.]


In [39]:
arr = np.array([1,2,3], dtype = bool)
print(arr)

[ True  True  True]


In [40]:
arr = np.array([1,2,3], dtype = complex)
print(arr)

[1.+0.j 2.+0.j 3.+0.j]


In [41]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [44]:
a = np.full((2,3,4),9)
a

array([[[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]]])

In [45]:
# Broadcasting
matrix = np.array([[1,2,4],
                   [4,5,6]])

In [47]:
# Add a scalar to each row
broadcasting = matrix + np.array([10, 20, 30])
broadcasting

array([[11, 22, 34],
       [14, 25, 36]])

In [51]:
broadcasting_column = matrix*3
broadcasting_column

array([[ 3,  6, 12],
       [12, 15, 18]])

In [54]:
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[4,5], [5,6]])
matrix_multiplication = np.matmul(mat1, mat2)
matrix_multiplication

array([[14, 17],
       [32, 39]])

In [55]:
matrix_determinant = np.linalg.det(mat1)
matrix_determinant

np.float64(-2.0000000000000004)

In [56]:
matrix_inverse = np.linalg.inv(mat1)
matrix_inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [58]:
arr1 = np.array([1,2,4])
exponential_values = np.exp(arr1)
exponential_values

array([ 2.71828183,  7.3890561 , 54.59815003])

In [61]:
log_values = np.log(arr1)
log_values

array([0.        , 0.69314718, 1.38629436])

In [63]:
log10_values = np.log10(arr1)
log10_values

array([0.        , 0.30103   , 0.60205999])

In [69]:
a = np.array([[1,2,3,4,5,6],
              [7,8,9,10,11,12],
              [13,14,15,16,17,18],
               [19,20,21,22,23,24]])
np.save("myarray.npy",a)

In [68]:
a = np.load("myarray.npy")
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [ ]:
# Weather app using API (Application Program Interface)
## Fetch data from public weather weather api
## Process
## Display useful info
## API - fetch, send, interact with external services
## Weather data, financial market data

%pip install requests

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [requests]
Note: you may need to restart the kernel to use updated packages.


In [ ]:
## Weather App using OpenWeatherMap API
import requests

## API Setup
API_KEY = "383340e922efc19f3360f7cdb4d74d42"
BASE_URL = "https://api.openweathermap.org/data/2.5/weather"

## Get Weather Data
def get_weather(city):
    try:
        url = f"{BASE_URL}?q={city}&appid={API_KEY}&units=metric"
        response = requests.get(url)
        data= response.json()
        if response.status_code == 200:
            data=response.json()
            weather = {
                "City": data["name"],
                "Temperature": f"{data['main']['temp']}C",
                "Weather": data["weather"][0]['description'].title(),
                "Humidity": f"{data['main']['humidity']}%", 
                "Wind Speed": f"{data['wind']['speed']}m/s"
            }
            return weather
        elif response.status_code == 404:
            print("City not found")
        else:
            print("An error occured. Status Code: ", response.status.code)
    except Exception as e:
        print("error Occured: ", e)
    return None

## Display the weather information
def display_weather(weather):
    print("\n---Weather Information---")
    for key,value in weather.items():
        print(f"{key}: {value}")

## Main Program Loop
while True:
    print("\n---Weather Information---")
    city = input("Enter a city name (or 'q' to quit): ").strip()
    if city.lower() == 'q':
        break
    weather = get_weather(city)
    if weather:
        display_weather(weather)


---Weather Information---

---Weather Information---
City: Kathmandu
Temperature: 25.55C
Weather: Overcast Clouds
Humidity: 78%
Wind Speed: 1.77m/s

---Weather Information---


In [1]:
%pip install pandas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 4.0 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [pandas]2m2/3 [pandas]
Note: you may need to restart the kernel to use updated packages.
