In [1]:
import numpy as np 

In [2]:
a=np.zeros(10)
print(a)
type(a[0])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


numpy.float64

In [4]:
type(a[1])
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
a=np.ones(10)
print(a)
type(a[0])

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


numpy.float64

In [7]:
a=np.(10)
print(a)
type(a[0])

SyntaxError: invalid syntax (3793471156.py, line 1)

In [8]:
a=np.empty(10)
print(a)
type(a[0])

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


numpy.float64

In [9]:
z=np.zeros(5)
print(z.shape)

(5,)


In [10]:
z.shape=(5,1)

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
e=np.eye(3)

In [16]:
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9]])
z=np.concatenate((arr1,arr2),axis=0)
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
arr2=np.array([[7],
               [8]])
z=np.concatenate((arr1,arr2),axis=1)
print(z)

[[1 2 3 7]
 [4 5 6 8]]


In [21]:
a_list=[1,2,3,4,5,6,7,8,9]
z=np.concatenate(a_list)
print(z)

ValueError: zero-dimensional arrays cannot be concatenated

In [23]:
z=np.random.randint(1,100,size=50)
print(np.sort(z))

[ 5  7  7  9 11 12 15 17 18 21 26 29 31 31 37 40 41 42 45 49 50 52 53 54
 62 63 65 66 66 68 68 71 71 73 73 74 74 76 77 84 84 85 86 86 94 95 96 97
 97 98]


In [24]:
z[0:2]

array([71, 73], dtype=int32)

In [29]:
a=np.array([[1,2,3],
           [4,5,6]])
print(a)
print(a[1,1])

[[1 2 3]
 [4 5 6]]
5


In [30]:
a.ndim

2

In [31]:
a=np.append(a,[[7,8,9]],axis=0)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
a.ndim

2

In [34]:
a=np.append(a,[[7,8,9]])
print(a)

[1 2 3 4 5 6 7 8 9 7 8 9]


In [49]:
a=np.array([[1,2,3],
           [4,5,6]])
a=np.insert(a,1,[11,23,45
                 ],axis=0)
print(a)

[[ 1  2  3]
 [11 23 45]
 [ 4  5  6]]


In [50]:
a=np.delete(a,1,0)
print(a)

[[1 2 3]
 [4 5 6]]


In [51]:
a=np.delete(a,1,1)
print(a)

[[1 3]
 [4 6]]


In [ ]:
%pip install scikit-image

^C
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


  Using cached scikit_image-0.25.2-cp313-cp313-win_amd64.whl.metadata (14 kB)
  Using cached scipy-1.15.3-cp313-cp313-win_amd64.whl.metadata (60 kB)
  Using cached networkx-3.5-py3-none-any.whl.metadata (6.3 kB)
  Using cached pillow-11.2.1-cp313-cp313-win_amd64.whl.metadata (9.1 kB)
  Using cached imageio-2.37.0-py3-none-any.whl.metadata (5.2 kB)
  Using cached tifffile-2025.6.11-py3-none-any.whl.metadata (32 kB)
  Using cached lazy_loader-0.4-py3-none-any.whl.metadata (7.6 kB)
Using cached scikit_image-0.25.2-cp313-cp313-win_amd64.whl (12.9 MB)
Using cached imageio-2.37.0-py3-none-any.whl (315 kB)
Using cached lazy_loader-0.4-py3-none-any.whl (12 kB)
Using cached networkx-3.5-py3-none-any.whl (2.0 MB)
Using cached pillow-11.2.1-cp313-cp313-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/41.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/41.0 MB ? eta -:--:--
    --------------------------------------- 0.8/41.0 MB 2.6 MB/s eta 0:00:16
   - ---

In [55]:
from skimage import io
photo=io.imread(r'C:\pythonclass2\flower.png')
type(photo)


numpy.ndarray

In [ ]:
%pip install matplotlib

In [ ]:
import matplotlib.pyplot as plt
plt.imshow(photo)
photo.shape