In [2]:
%pip install matplotlib


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
%pip install scikit-image

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np

z = np.array([1, 2, 3, 4, 5])
z < 3

array([ True,  True, False, False, False])

In [8]:
#print only the values which shows true
print(z[z < 3])

[1 2]


In [10]:
#add two arrays
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x + y)

[5 7 9]


In [14]:
arr1= np.array([1,2,3,4,5])
arr2= np.array([6,7,8,9,10])
arr1 + arr2
z=np.power(arr1,3)
z

array([  1,   8,  27,  64, 125])

In [16]:
arr1 + 30

array([31, 32, 33, 34, 35])

In [18]:
arr1 @ arr2

np.int64(130)

In [20]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [22]:
#find dimension size
a1= np.arange(10)
a2= np.arange(12).reshape(2,6)
a3= np.arange(8).reshape(2,2,2,)
np.ndim(a1)# 2 blocks of 2 row and 2 column

1

In [24]:
a3.size
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [27]:
#DATA TYPES
# FLOAT BOOL COMPLEX

arr=np.array([1,2,3,4,5], dtype=float)
print (arr)

[1. 2. 3. 4. 5.]


In [29]:
#3D ARRAY
arr3 = np.array([[[1, 2,3], [ 4,5,6]], [[7,8,9], [10,11,12]]])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [31]:
a=np.full((2,3,4), 9)
a

array([[[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]]])

In [34]:
#BOARDCASTING 

matrix=np.array([[1,2,3],
                [4,5,6]])



In [ ]:
# add a scalar to each row

boardcasting= matrix + np.array([10,20,30]) #add corresponding element of the array to each row
boardcasting

array([[11, 22, 33],
       [14, 25, 36]])

In [38]:
broadcasting_column =matrix * 3
broadcasting_column

array([[ 3,  6,  9],
       [12, 15, 18]])

In [47]:
# Use a square submatrix (2x2) from 'matrix'
square_matrix = np.array([[1,2],[3,4]])
matrix_determinant = np.linalg.det(square_matrix)
matrix_inverse = np.linalg.inv(square_matrix)

In [50]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
exponential_values = np.exp(arr1)
exponential_values

array([ 2.71828183,  7.3890561 , 20.08553692])

In [52]:
a= np.array([[1, 2, 3, 4, 5,6],
            [7, 8, 9, 10, 11,12],
            [13, 14, 15, 16, 17,18],
            [19, 20, 21, 22, 23,24]])
np.save("myarray.npy",a)
a= np.load("myarray.npy")
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [54]:
#WEATHER APP USING API(APPLICATION PROGRAMMING INTERFACE)
%pip install requests

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [55]:
#https://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}

#API_KEY="7c9b14120aa59d2f604787021bfaf159"



In [58]:
import requests
 #API SETUP
API_KEY= "7c9b14120aa59d2f604787021bfaf159"
BASE_URL = "http://api.openweathermap.org/data/2.5/weather"

#GET WEATHER DATA
def get_weather(city):
    try:
        url = f"{BASE_URL}?q={city}&appid={API_KEY}&units=metric"
        response = requests.get(url)
        data= response.json()
        if response.status_code == 200:
            data=response.json()
            weather = {
                "City": data["name"],
                "Temperature": f"{data['main']['temp']}C",
                "Weather": data["weather"][0]['description'].title(),
                "Humidity": f"{data['main']['humidity']}%", 
                "Wind Speed": f"{data['wind']['speed']}m/s"
            }
            return weather
        elif response.status_code == 404:
            print("City not found")
        else:
            print("An error occured. Status Code: ", response.status.code)
    except Exception as e:
        print("error Occured: ", e)
    return None

## Display the weather information
def display_weather(weather):
    print("\n---Weather Information---")
    for key,value in weather.items():
        print(f"{key}: {value}")

## Main Program Loop
while True:
    print("\n---Weather Information---")
    city = input("Enter a city name (or 'q' to quit): ").strip()
    if city.lower() == 'q':
        break
    weather = get_weather(city)
    if weather:
        display_weather(weather)




---Weather Information---

---Weather Information---
City: Argentina
Temperature: 6.27C
Weather: Clear Sky
Humidity: 47%
Wind Speed: 3.51m/s

---Weather Information---

---Weather Information---
City: Kathmandu
Temperature: 25.55C
Weather: Overcast Clouds
Humidity: 78%
Wind Speed: 1.77m/s

---Weather Information---

---Weather Information---
City: London
Temperature: 24.74C
Weather: Overcast Clouds
Humidity: 53%
Wind Speed: 3.88m/s

---Weather Information---
City not found

---Weather Information---
City not found

---Weather Information---


In [59]:
#INTRODUCTIO TO PANDAS
%pip install pandas

   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.0 MB 1.1 MB/s eta 0:00:10
   -- ------------------------------------- 0.8/11.0 MB 1.2 MB/s eta 0:00:09
   ---- ----------------------------------- 1.3/11.0 MB 1.5 MB/s eta 0:00:07
   ------ --------------------------------- 1.8/11.0 MB 1.6 MB/s eta 0:00:06
   -------- ------------------------------- 2.4/11.0 MB 1.7 MB/s eta 0:00:05
   ---------- ----------------------------- 2.9/11.0 MB 1.9 MB/s eta 0:00:05
   ------------ --------------------------- 3.4/11.0 MB 2.0 MB/s eta 0:00:04
   --------------- ------------------------ 4.2/11.0 MB 2.1 MB/s eta 0:00:04
   ----------------- ---------------------- 4.7/11.0 MB 2.2 MB/s eta 0:00:03
   ------------------- -------------------- 5.2/11.0 MB 2.2 MB/s eta 0:00:03
   -----------------


[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip
