In [1]:
import numpy as np 

In [7]:
a=np.zeros(10)
print(a)
type(a[0])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


numpy.float64

In [12]:
arr1 =np.array([[1,2,3],
               [4,5,6]])
arr2=np.array([[7,8,9]])
z=np.concatenate((arr1,arr2,),axis=0)
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2=np.array([[7],
              [8]])
z=np.concatenate((arr1,arr2),axis=1)
z


array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

In [15]:
a_list = [1,2,3,4,5,6,7,8,9]
z=np.concatenate(a_list)
print(z)

ValueError: zero-dimensional arrays cannot be concatenated

In [16]:
z=np.random.randint(1,51,size=50)
print(np.sort(z))

[ 1  1  2  3  3  3  3  5  5  7  7 10 12 12 14 15 16 17 18 18 18 18 19 20
 22 22 22 23 28 29 29 30 31 34 34 36 37 37 38 40 41 43 44 46 47 48 49 50
 50 50]


In [17]:
z[0:2]
z[::-1]

array([ 1, 50, 44, 20, 19, 17, 18,  3,  5, 43, 22,  1, 37, 34,  3,  3, 18,
       50,  5, 18, 34, 12, 31,  2, 15,  3, 41, 40, 22, 46, 18, 29, 23, 10,
       37, 50,  7, 30, 22, 36, 38, 14, 48, 12, 16, 49, 29, 47,  7, 28],
      dtype=int32)

In [19]:
a=np.array([[1,2,3],
           [4,5,6]])
print(a[1,1])

5


In [31]:
a.ndim

1

In [32]:
a=np.append(a,[[7,8,9]],axis=0)
print (a)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [23]:
a.ndim

2

In [25]:
a=np.append(a,[[7,8,9]])
print(a)

[1 2 3 4 5 6 7 8 9 7 8 9 7 8 9 7 8 9]


In [41]:
a=np.array([[1,2,3],
           [4,5,6]])

a=np.insert(a,1,[7,8,9],axis=0)
print(a)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [42]:
a=np.array([[1,2,3],
           [4,5,6]])
a=np.delete(a,1,0)
print(a)

[[1 2 3]]


In [51]:
a=np.array([[1,2,3],
           [4,5,6]])

a=np.delete(a,1,1)
print(a)

[[1 3]
 [4 6]]


In [52]:
%pip install scikit-image 

   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.9 MB 5.7 MB/s eta 0:00:03
   ------ --------------------------------- 2.1/12.9 MB 6.6 MB/s eta 0:00:02
   ------------- -------------------------- 4.2/12.9 MB 7.9 MB/s eta 0:00:02
   ----------------- ---------------------- 5.8/12.9 MB 7.7 MB/s eta 0:00:01
   --------------------- ------------------ 7.1/12.9 MB 7.5 MB/s eta 0:00:01
   -------------------------- ------------- 8.4/12.9 MB 7.3 MB/s eta 0:00:01
   ------------------------------ --------- 10.0/12.9 MB 7.3 MB/s eta 0:00:01
   ------------------------------------ --- 11.8/12.9 MB 7.4 MB/s eta 0:00:01
   ---------------------------------------- 12.9/12.9 MB 7.4 MB/s eta 0:00:00
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ------------------------------------ --- 1.8/2.0 MB 13.0 MB/s eta 0:00:01
   ---------------------------------------- 2.0/2.0 MB 8.7 MB/s eta 0:00:00
   ---------


[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
from  skimage import io
photo = io.imread(r'C:\python02\kk1.jpeg')
type(photo)

numpy.ndarray

In [ ]:
%pip install matplotib

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement matplotib (from versions: none)

[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for matplotib


In [1]:
%pip install matplotib

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement matplotib (from versions: none)

[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for matplotib


In [3]:
import matplotlib.pyplot as plt

In [4]:
print(np.sum(photo))
print(np.prod(photo))
print(np.mean(photo))
print(np.std(photo))
print(np.var(photo))
print(np.min(photo))
print(np.max(photo))
print(np.argmin(photo))
print(np.argmax(photo))


17971614
0
118.93067301965456
102.68220484155333
10543.63519112272
0
255
126
36605


In [6]:
z=np.array([1,2,3,4,5])
z<3


array([ True,  True, False, False, False])

In [12]:
z[z<3]

array([1, 2])

In [14]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
arr1+arr2
z=np.power(arr1,3)
print(z)

[  1   8  27  64 125]


In [ ]:
z=z+30
print(z)

[ 31  38  57  94 155]


In [16]:
arr1@arr2
print(z)

[ 31  38  57  94 155]


In [33]:
np.arange(1,13).reshape(6,2)


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [24]:
a1=np.arange(10)
a2=np.arange(12).reshape(2,6)
print(a2)
a3=np.arange(8).reshape(2,2,2)
np.ndim(a1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


1

In [31]:
arr=np.array([1,2,3]).dtype=float
print(arr)

<class 'float'>


In [41]:
arr3=np.array([[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]])
print(arr3)


TypeError: Field elements must be 2- or 3-tuples, got '[7, 8, 9]'

In [40]:
a=np.full([2,3,4],0)
print(a)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [44]:
matrix = np.array([[1,2,3],
                  [4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [47]:
broadcasting=matrix+np.array([10,20,30])
print(broadcasting)

[[11 22 33]
 [14 25 36]]


In [49]:
np.ndim([10,20,30])


1

In [50]:
broadcasting_column=matrix*3
print(broadcasting_column)

[[ 3  6  9]
 [12 15 18]]


matrix1=np.array([[1,2,3],[4,5,6]])
matrix2=np.array([[7,8,9],[10,11,12]])


In [63]:
matrix1=np.array([[1,2],[4,5]])
matrix2=np.array([[6,7],[8,9]])


matrix_determinant=np.linalg.det(matrix1)
matrix_inverse=np.linalg.inv(matrix1)
print(matrix_determinant)
print(matrix_inverse)

-2.9999999999999996
[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


In [62]:
a=np.array([[1,2,3,4,5,6],
           [7,8,9,10,11,12],
           [13,14,15,16,17,18],
            [19,20,21,22,23,24]])
np.save("myarray.npy",a)
a=np.load("myarray.npy")
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [ ]:
{"cod":401, "message": "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."}

In [ ]:
ca6e44e4c5a4960eb4eaf12acba317f6

In [3]:
%pip install requests 

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
API_KEY = "06b8db9a7daa0a22d9a21056d4cbcb60"
BASE_URL = "https://api.openweathermap.org/data/2.5/weather"

## Get Weather Data
def get_weather(city):
    try:
        url = f"{BASE_URL}?q={city}&appid={API_KEY}&units=metric"
        response = requests.get(url)
        data= response.json()
        if response.status_code == 200:
            data=response.json()
            weather = {
                "City": data["name"],
                "Temperature": f"{data['main']['temp']}C",
                "Weather": data["weather"][0]['description'].title(),
                "Humidity": f"{data['main']['humidity']}%", 
                "Wind Speed": f"{data['wind']['speed']}m/s"
            }
            return weather
        elif response.status_code == 404:
            print("City not found")
        else:
            print("An error occured. Status Code: ", response.status.code)
    except Exception as e:
        print("error Occured: ", e)
    return None

## Display the weather information
def display_weather(weather):
    print("\n---Weather Information---")
    for key,value in weather.items():
        print(f"{key}: {value}")

## Main Program Loop
while True:
    print("\n---Weather Information---")
    city = input("Enter a city name (or 'q' to quit): ").strip()
    if city.lower() == 'q':
        break
    weather = get_weather(city)
    if weather:
        display_weather(weather)





---Weather Information---
error Occured:  name 'requests' is not defined

---Weather Information---
error Occured:  name 'requests' is not defined

---Weather Information---
