# Introduction to NumPy

 NumPy (Numerical Python) is an open-source extension module for Python, which provides fast, efficient, and versatile tools for working with arrays and matrices. It is the backbone of most data science and machine learning libraries in Python (e.g., Pandas, SciPy, Scikit-learn, TensorFlow, PyTorch).

Why NumPy?

Performance: NumPy operations are implemented in C, making them significantly faster than equivalent Python list operations, especially for large datasets. This speed is critical for scientific and engineering computations.

Memory Efficiency: NumPy arrays are more memory-efficient than Python lists because they store elements of the same data type contiguously in memory.

Functionality: It provides a vast collection of high-level mathematical functions to operate on these arrays, covering linear algebra, Fourier transforms, random number generation, etc.

Ecosystem: It's the standard for numerical data interchange in the Python scientific computing ecosystem.

Let's dive in!

# 1. Installation

NumPy is typically included with scientific Python distributions like Anaconda. If you don't have it, you can install it using pip:

In [ ]:
!pip install numpy

Once installed, you can import it, conventionally as np:

In [1]:
import numpy as np
print(f"NumPy Version: {np.__version__}")

NumPy Version: 1.26.4


# 2. Core Concepts

### 2.1 The ndarray Object: N-dimensional Array

The most important object in NumPy is the ndarray (N-dimensional array). It's a grid of values, all of the same type, and is indexed by a tuple of non-negative integers.

ndim: The number of dimensions (axes) of the array.

shape: A tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m).

size: The total number of elements in the array.

dtype: An object describing the data type of the elements in the array.

Example:

In [ ]:
# Create a 1-dimensional array (vector)
arr1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr1d)
print(f"Dimensions (ndim): {arr1d.ndim}")
print(f"Shape (shape): {arr1d.shape}")
print(f"Size (size): {arr1d.size}")
print(f"Data Type (dtype): {arr1d.dtype}")

print("\n" + "="*30 + "\n")

# Create a 2-dimensional array (matrix)
arr2d = np.array([[10, 20, 30], [40, 50, 60]])
print("2D Array:")
print(arr2d)
print(f"Dimensions (ndim): {arr2d.ndim}")
print(f"Shape (shape): {arr2d.shape}")
print(f"Size (size): {arr2d.size}")
print(f"Data Type (dtype): {arr2d.dtype}")

### 2.2 Data Types (dtype)

NumPy supports a much wider range of numerical data types than Python's built-in types. This allows for fine-grained control over memory usage and precision.

Common dtype examples:

int8, int16, int32, int64: Signed integers of different sizes.

uint8, uint16, uint32, uint64: Unsigned integers.

float16, float32, float64: Floating-point numbers (single and double precision). float64 is often default.

complex64, complex128: Complex numbers.

bool: Boolean values (True/False).

str, U: String (variable length, 'U' is Unicode).

You can explicitly specify the dtype when creating an array:

In [ ]:
arr_float = np.array([1, 2, 3], dtype=np.float64)
print(f"Array with float64 dtype: {arr_float}, Dtype: {arr_float.dtype}")

arr_int8 = np.array([100, 120, -50], dtype=np.int8)
print(f"Array with int8 dtype: {arr_int8}, Dtype: {arr_int8.dtype}")

arr_bool = np.array([0, 1, 0, 1], dtype=bool)
print(f"Array with boolean dtype: {arr_bool}, Dtype: {arr_bool.dtype}")

# Type casting (changing dtype)
arr_mixed = np.array([1.5, 2.7, 3.1])
arr_int_casted = arr_mixed.astype(int)
print(f"Original float array: {arr_mixed}")
print(f"Casted to int: {arr_int_casted}, Dtype: {arr_int_casted.dtype}")

### 2.3 Array Creation Routines

NumPy provides many functions to create arrays beyond converting Python lists.

In [ ]:
# From a Python list or tuple
list_data = [1, 2, 3]
array_from_list = np.array(list_data)
print(f"Array from list: {array_from_list}")

In [ ]:
#np.zeros(shape, dtype=float) #Create an array filled with zeros.
zeros_1d = np.zeros(5,dtype=int)
print(f"1D Zeros: {zeros_1d}")
zeros_2d = np.zeros((2, 3))
print(f"2D Zeros:\n{zeros_2d}")

In [ ]:
#np.ones(shape, dtype=float): #Create an array filled with ones.
ones_3d = np.ones((2, 2, 2))
print(f"3D Ones:\n{ones_3d}")

In [ ]:
#np.empty(shape, dtype=float): #Create an array without initializing its entries. Faster, but contains arbitrary values.
empty_arr = np.empty((3, 3))
print(f"Empty array (uninitialized):\n{empty_arr}") # Values will vary

In [ ]:
#np.arange(start, stop, step): #Create an array with evenly spaced values within a given interval (like Python's range()).
arr_range = np.arange(0, 10, 2) # [0, 2, 4, 6, 8]
print(f"Array using arange: {arr_range}")

In [ ]:
#np.linspace(start, stop, num): Create an array with evenly spaced numbers over a specified interval. num is the number of samples.
arr_linspace = np.linspace(0, 1, 5) # 5 points between 0 and 1, inclusive
print(f"Array using linspace: {arr_linspace}")

In [ ]:
#np.full(shape, fill_value, dtype=None): Create an array of a given shape filled with fill_value.
full_arr = np.full((2, 2), 7)
print(f"Full array:\n{full_arr}")

In [ ]:
#np.eye(N) / np.identity(N): Create an identity matrix (2-D array with ones on the diagonal and zeros elsewhere).
identity_matrix = np.eye(3)
print(f"Identity matrix:\n{identity_matrix}")

In [ ]:
#Random Arrays: See Section 6 for more details.
random_uniform = np.random.rand(2, 2) # Uniform distribution [0, 1)
print(f"Random uniform:\n{random_uniform}")
random_normal = np.random.randn(2, 2) # Standard normal distribution
print(f"Random normal:\n{random_normal}")

# 3. Array Operations

NumPy's power comes from its ability to perform operations on entire arrays without explicit loops (vectorization).

### 3.1 Basic Arithmetic Operations (Element-wise)

Arithmetic operations (+, -, *, /, %) are performed element-wise.

In [ ]:
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])

print(f"arr_a + arr_b: {arr_a + arr_b}")
print(f"arr_a - arr_b: {arr_a - arr_b}")
print(f"arr_a * arr_b (element-wise multiplication): {arr_a * arr_b}")
print(f"arr_a / arr_b: {arr_a / arr_b}")
print(f"arr_a ** 2 (element-wise power): {arr_a ** 2}")

# Operations with a scalar
print(f"arr_a + 10: {arr_a + 10}")
print(f"arr_a * 5: {arr_a * 5}")

# Comparison operations (element-wise, returns boolean array)
print(f"arr_a > 2: {arr_a > 2}")
print(f"arr_a == arr_b: {arr_a == arr_b}")

### 3.2 Broadcasting

Broadcasting is NumPy's way of dealing with arrays of different shapes during arithmetic operations. Subject to certain constraints, the smaller array is "broadcast" across the larger array so that they have compatible shapes.

Rules of Broadcasting:

If the arrays do not have the same number of dimensions, the shape of the smaller array is padded with ones on its left side.

If the shape of the two arrays does not match in any dimension, and neither dimension has a size of 1, an error is raised.

Dimensions with a size of 1 are stretched to match the other array's size.

# Example 1: Scalar broadcast to array
arr = np.array([1, 2, 3])
scalar = 5
result = arr + scalar
print(f"Array + scalar:\n{result}")

# Example 2: 1D array broadcast to 2D array
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])
arr1d = np.array([10, 20, 30])
result_broadcast = arr2d + arr1d
print(f"2D array + 1D array (broadcasting rows):\n{result_broadcast}")

# Example 3: Column vector broadcast to 2D array
arr_col_vector = np.array([[100],
                           [200]])
result_col_broadcast = arr2d + arr_col_vector
print(f"2D array + column vector (broadcasting columns):\n{result_col_broadcast}")

# Incompatible shapes (will raise ValueError)
# arr_bad_shape = np.array([1, 2])
# arr2d + arr_bad_shape

### 3.3 Mathematical Functions

NumPy provides a wide range of universal functions (ufuncs) that operate element-wise on arrays.

In [ ]:
arr = np.array([0, np.pi/2, np.pi])

print(f"np.sin(arr): {np.sin(arr)}")
print(f"np.cos(arr): {np.cos(arr)}")
print(f"np.exp(arr): {np.exp(arr)}") # e^x
print(f"np.log(arr + 1): {np.log(arr + 1)}") # natural logarithm
print(f"np.sqrt(arr): {np.sqrt(arr)}")

# Rounding functions
arr_float_vals = np.array([1.2, 2.7, 3.5, 4.1])
print(f"np.round(arr_float_vals): {np.round(arr_float_vals)}")
print(f"np.floor(arr_float_vals): {np.floor(arr_float_vals)}")
print(f"np.ceil(arr_float_vals): {np.ceil(arr_float_vals)}")

### 3.4 Aggregation Functions

These functions compute a single value from an array or along a specific axis.

In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print(f"Sum of all elements: {matrix.sum()}")
print(f"Mean of all elements: {matrix.mean()}")
print(f"Minimum element: {matrix.min()}")
print(f"Maximum element: {matrix.max()}")
print(f"Standard deviation: {matrix.std()}")

# Aggregation along a specific axis
# axis=0 means operations down the columns
print(f"Sum along axis=0 (columns): {matrix.sum(axis=0)}")
# axis=1 means operations across the rows
print(f"Mean along axis=1 (rows): {matrix.mean(axis=1)}")

# argmin, argmax: return indices of min/max values
print(f"Index of min element: {matrix.argmin()}") # flat index
print(f"Indices of max element along axis=1: {matrix.argmax(axis=1)}")

# 4. Indexing and Slicing

Accessing elements or sub-arrays in NumPy is flexible and powerful.

### 4.1 Basic Indexing

Similar to Python lists, but for multiple dimensions.

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(f"Element at index 0: {arr[0]}")
print(f"Element at last index: {arr[-1]}")

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(f"Element at (row 0, col 1): {matrix[0, 1]}") # or matrix[0][1]
print(f"Element at (row 2, col 2): {matrix[2, 2]}")

### 4.2 Slicing

Extracting sub-arrays using start:stop:step.

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(f"Slice from index 2 to 5 (exclusive): {arr[2:5]}") # [30, 40, 50]
print(f"Slice from beginning to index 3: {arr[:4]}")     # [10, 20, 30, 40]
print(f"Slice from index 4 to end: {arr[4:]}")           # [50, 60, 70]
print(f"Every other element: {arr[::2]}")                # [10, 30, 50, 70]
print(f"Reversed array: {arr[::-1]}")                  # [70, 60, 50, 40, 30, 20, 10]

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(f"First row: {matrix[0, :]}") # or matrix[0]
print(f"First column: {matrix[:, 0]}")
print(f"Sub-matrix (rows 0-1, cols 1-2):\n{matrix[0:2, 1:3]}") # [[2,3], [5,6]]

# Slices return views, not copies!
# Modifying a slice will modify the original array.
sliced_view = matrix[0, :]
sliced_view[0] = 99
print(f"\nOriginal matrix after modifying slice:\n{matrix}")

# To get a copy, use .copy()
matrix_copy = np.array([[1, 2, 3], [4, 5, 6]])
copy_view = matrix_copy[:, 1].copy()
copy_view[0] = 88
print(f"\nOriginal matrix_copy (unaffected by copy_view change):\n{matrix_copy}")

### 4.3 Boolean Indexing (Masking)

Select elements based on a boolean condition. Returns a 1D array.

In [ ]:
data = np.array([10, 5, 20, 12, 8, 30])
condition = data > 10
print(f"Boolean condition (data > 10): {condition}")
print(f"Elements greater than 10: {data[condition]}") # Uses the boolean array as an index

# Combined conditions
print(f"Elements between 10 and 20: {data[(data > 10) & (data < 20)]}")

# Modifying elements based on a condition
data[data < 10] = 0
print(f"Data after setting values less than 10 to 0: {data}")

### 4.4 Fancy Indexing

Using integer arrays (or lists) to select arbitrary elements.

In [2]:
arr = np.array(['a', 'b', 'c', 'd', 'e', 'f'])
indices = np.array([0, 3, 5])
print(f"Elements at specific indices: {arr[indices]}")

matrix = np.arange(16).reshape((4, 4))
print(f"\nOriginal matrix:\n{matrix}")

# Select specific rows and columns
rows = np.array([0, 2])
cols = np.array([1, 3])
print(f"Elements from matrix[rows, cols]: {matrix[rows, cols]}") # (0,1) and (2,3) -> [1, 11]

# Select multiple rows
print(f"Rows 0 and 2:\n{matrix[[0, 2]]}")

# Select specific elements using a list of coordinate pairs
coords = np.array([[0, 0], [1, 2], [3, 1]])
print(f"Elements at coordinate pairs: {matrix[coords[:, 0], coords[:, 1]]}") # (0,0), (1,2), (3,1) -> [0, 6, 13]

Elements at specific indices: ['a' 'd' 'f']

Original matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Elements from matrix[rows, cols]: [ 1 11]
Rows 0 and 2:
[[ 0  1  2  3]
 [ 8  9 10 11]]
Elements at coordinate pairs: [ 0  6 13]


# 5. Reshaping and Resizing

Changing the shape of an array.

### 5.1 reshape()

Returns a new array with the same data but a new shape. The total number of elements must remain the same.

In [6]:
arr = np.arange(12) # 1D array with 12 elements
print(f"Original 1D array: {arr}")

matrix_3x4 = arr.reshape(3, 4)
print(f"Reshaped to 3x4 matrix:\n{matrix_3x4}")

matrix_2x2x3 = arr.reshape(2, 2, 3)
print(f"Reshaped to 2x2x3 3D array:\n{matrix_2x2x3}")

# Use -1 to let NumPy infer the dimension
matrix_4x_ = arr.reshape(4, -1) # Will infer (4, 3)
print(f"Reshaped to 4x? matrix:\n{matrix_4x_}")

# Reshape is a view if possible, otherwise a copy.
# If you modify the reshaped array, the original may also change.
matrix_3x4[0, 0] = 999
print(f"Original array after modifying reshaped view: {arr}")

Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4 matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to 2x2x3 3D array:
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Reshaped to 4x? matrix:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Original array after modifying reshaped view: [999   1   2   3   4   5   6   7   8   9  10  11]


### 5.2 resize()

Changes the shape of an array in-place. Can add or remove elements. If the new array is larger, new elements are filled with zeros.

In [7]:
arr = np.arange(5)
print(f"Original array: {arr}")
arr.resize((2, 3)) # Resizes in-place to 2x3, adding a zero
print(f"Resized array (in-place):\n{arr}")

arr.resize((1, 2)) # Resizes in-place to 1x2, truncating
print(f"Resized array (smaller, in-place):\n{arr}")

Original array: [0 1 2 3 4]
Resized array (in-place):
[[0 1 2]
 [3 4 0]]
Resized array (smaller, in-place):
[[0 1]]


Note: resize() is less common than reshape() because it modifies the array in-place and can lead to data loss or padding.

### 5.3 ravel() and flatten()

Convert a multi-dimensional array into a 1D array.

ravel(): Returns a view of the original array (if possible). Modifying the raveled array might modify the original.

flatten(): Returns a copy of the array. Modifying the flattened array will not affect the original.

In [8]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Original matrix:\n{matrix}")

raveled_arr = matrix.ravel()
print(f"Raveled array: {raveled_arr}")
raveled_arr[0] = 99
print(f"Original matrix after modifying raveled view:\n{matrix}") # Original changed

matrix = np.array([[1, 2, 3], [4, 5, 6]]) # Reset matrix
flattened_arr = matrix.flatten()
print(f"Flattened array: {flattened_arr}")
flattened_arr[0] = 100
print(f"Original matrix after modifying flattened copy:\n{matrix}") # Original unchanged

Original matrix:
[[1 2 3]
 [4 5 6]]
Raveled array: [1 2 3 4 5 6]
Original matrix after modifying raveled view:
[[99  2  3]
 [ 4  5  6]]
Flattened array: [1 2 3 4 5 6]
Original matrix after modifying flattened copy:
[[1 2 3]
 [4 5 6]]


### 5.4 transpose() / .T

Permutes the dimensions of an array. For 2D arrays, it swaps rows and columns.

In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print(f"Original matrix:\n{matrix}")
print(f"Transposed matrix:\n{matrix.T}")
print(f"Transposed matrix (using transpose()):\n{np.transpose(matrix)}")

# For higher dimensions, it permutes axes
arr_3d = np.arange(24).reshape((2, 3, 4))
print(f"\nOriginal 3D array (shape {arr_3d.shape}):\n{arr_3d}")
# Swap axes 0 and 1
arr_3d_transposed = arr_3d.transpose((1, 0, 2)) # (rows, depth, cols) -> (depth, rows, cols)
print(f"Transposed 3D array (shape {arr_3d_transposed.shape}):\n{arr_3d_transposed}")

# 6. Stacking and Splitting Arrays

Combining or dividing arrays.

### 6.1 Stacking Arrays

In [ ]:
np.concatenate((arr1, arr2, ...), axis=0): Joins a sequence of arrays along an existing axis.

In [ ]:
np.stack((arr1, arr2, ...), axis=0): Joins a sequence of arrays along a new axis.

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenate along existing axis (axis=0 for 1D arrays)
concatenated = np.concatenate((arr1, arr2))
print(f"Concatenated 1D arrays: {concatenated}")

mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

# Concatenate row-wise (along axis=0)
conc_rows = np.concatenate((mat1, mat2), axis=0)
print(f"Concatenated (row-wise):\n{conc_rows}")

# Concatenate column-wise (along axis=1)
conc_cols = np.concatenate((mat1, mat2), axis=1)
print(f"Concatenated (column-wise):\n{conc_cols}")

# Stack creates a new dimension
stacked = np.stack((arr1, arr2), axis=0) # Stacks them as rows
print(f"Stacked (axis=0):\n{stacked}")
stacked_col = np.stack((arr1, arr2), axis=1) # Stacks them as columns
print(f"Stacked (axis=1):\n{stacked_col}")

### 6.2 Convenience Stacking Functions

In [ ]:
np.hstack((arr1, arr2, ...)): Stack arrays in sequence horizontally (column-wise). Equivalent to np.concatenate(..., axis=1).

In [ ]:
np.vstack((arr1, arr2, ...)): Stack arrays in sequence vertically (row-wise). Equivalent to np.concatenate(..., axis=0).

In [ ]:
np.dstack((arr1, arr2, ...)): Stack arrays in sequence depth-wise (along the third axis).

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

hstacked = np.hstack((arr1, arr2))
print(f"Hstacked 1D arrays: {hstacked}")

vstacked = np.vstack((arr1, arr2))
print(f"Vstacked 1D arrays:\n{vstacked}")

mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

hstacked_2d = np.hstack((mat1, mat2))
print(f"Hstacked 2D arrays:\n{hstacked_2d}")

vstacked_2d = np.vstack((mat1, mat2))
print(f"Vstacked 2D arrays:\n{vstacked_2d}")

# dstack example (creates 3D array)
dstacked = np.dstack((mat1, mat2))
print(f"Dstacked 2D arrays (shape {dstacked.shape}):\n{dstacked}")

### 6.3 Splitting Arrays

In [ ]:
np.split(ary, indices_or_sections, axis=0): Split an array into multiple sub-arrays. indices_or_sections can be an integer (number of equal splits) or a list of indices where to split.

In [ ]:
np.hsplit(): Split an array into multiple sub-arrays horizontally (column-wise).

In [ ]:
np.vsplit(): Split an array into multiple sub-arrays vertically (row-wise).

In [ ]:
np.dsplit(): Split an array into multiple sub-arrays depth-wise.

In [3]:
arr = np.arange(12)
print(f"Original array: {arr}")

# Split into 3 equal sections
split_arrs = np.split(arr, 3)
print(f"Split into 3 equal parts: {split_arrs}")

# Split at specific indices
split_at_indices = np.split(arr, [2, 7]) # Splits before index 2 and before index 7
print(f"Split at indices [2, 7]: {split_at_indices}")

matrix = np.arange(16).reshape((4, 4))
print(f"\nOriginal matrix:\n{matrix}")

# Horizontal split (column-wise)
hsplit_matrix = np.hsplit(matrix, 2) # Split into 2 equal parts horizontally
print(f"Horizontal split:\n{hsplit_matrix[0]}\n---\n{hsplit_matrix[1]}")

# Vertical split (row-wise)
vsplit_matrix = np.vsplit(matrix, [1, 3]) # Split before row 1 and before row 3
print(f"Vertical split:\n{vsplit_matrix[0]}\n---\n{vsplit_matrix[1]}\n---\n{vsplit_matrix[2]}")

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Split into 3 equal parts: [array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]
Split at indices [2, 7]: [array([0, 1]), array([2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11])]

Original matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Horizontal split:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
---
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
Vertical split:
[[0 1 2 3]]
---
[[ 4  5  6  7]
 [ 8  9 10 11]]
---
[[12 13 14 15]]


# 7. Linear Algebra

NumPy provides robust support for linear algebra operations, leveraging highly optimized BLAS (Basic Linear Algebra Subprograms) libraries.

In [ ]:
### Create matrices
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
print(f"Matrix A:\n{A}")
print(f"Matrix B:\n{B}")

### Dot product (vector dot product or matrix multiplication for 2D arrays)
dot_product_A_B = np.dot(A, B)
print(f"Dot product (A . B):\n{dot_product_A_B}")

### Matrix multiplication (using @ operator or np.matmul)
matrix_mult_A_B = A @ B
print(f"Matrix multiplication (A @ B):\n{matrix_mult_A_B}")
print(f"Matrix multiplication (np.matmul(A, B)):\n{np.matmul(A, B)}")

### Element-wise multiplication (not matrix multiplication)
print(f"Element-wise multiplication (A * B):\n{A * B}")

### Determinant
det_A = np.linalg.det(A)
print(f"Determinant of A: {det_A}")

### Inverse of a matrix
try:
    inv_A = np.linalg.inv(A)
    print(f"Inverse of A:\n{inv_A}")
    # Verify A * A_inv is identity matrix
    print(f"A @ inv(A):\n{A @ inv_A}") # Should be identity matrix, might have tiny float errors
except np.linalg.LinAlgError:
    print("Matrix A is singular (no inverse).")

### Eigenvalues and Eigenvectors
### Returns (eigenvalues, eigenvectors)
eigenvals, eigenvecs = np.linalg.eig(A)
print(f"Eigenvalues of A: {eigenvals}")
print(f"Eigenvectors of A:\n{eigenvecs}")

### Solving linear equations Ax = b
### For example: 1x + 2y = 9, 3x + 4y = 10
### A = [[1, 2], [3, 4]], b = [9, 10]
b = np.array([9, 10])
x = np.linalg.solve(A, b)
print(f"Solution to Ax = b: x = {x}")
### Verify: A @ x should be close to b
print(f"A @ x (verification): {A @ x}")

### Singular Value Decomposition (SVD)
U, S, Vt = np.linalg.svd(A)
print(f"U from SVD:\n{U}")
print(f"Singular values S: {S}")
print(f"Vt from SVD:\n{Vt}")

9. File I/O with NumPy

NumPy provides functions to save and load arrays to/from disk efficiently.

9.1 Binary Files (.npy, .npz)

These are NumPy's native binary formats. They preserve dtype and shape information and are efficient for storing large arrays.

In [ ]:
np.save('filename.npy', array): Saves a single array to a binary .npy file.

In [ ]:
np.load('filename.npy'): Loads a single array from a .npy file.

In [ ]:
np.savez('filename.npz', array1=arr1, array2=arr2): Saves multiple arrays into a single uncompressed .npz archive. Can be accessed like a dictionary.

In [ ]:
np.savez_compressed('filename.npz', ...): Same as savez but compressed.

In [ ]:
data_to_save = np.arange(20).reshape(4, 5)
np.save('my_array.npy', data_to_save)
print(f"Saved array to my_array.npy:\n{data_to_save}")

loaded_data = np.load('my_array.npy')
print(f"Loaded array from my_array.npy:\n{loaded_data}")

# Saving multiple arrays
arr_a = np.array([1, 2, 3])
arr_b = np.linspace(0, 1, 5)
np.savez('multiple_arrays.npz', array_a=arr_a, array_b=arr_b)
print("\nSaved arr_a and arr_b to multiple_arrays.npz")

loaded_npz = np.load('multiple_arrays.npz')
print(f"Loaded array_a from .npz: {loaded_npz['array_a']}")
print(f"Loaded array_b from .npz: {loaded_npz['array_b']}")
loaded_npz.close() # Close the file handle when done

### Challenge: Modify a 5x5 Identity Matrix

**Task:**  
- Create a 5x5 identity matrix.
- Replace its central 3x3 submatrix with all 7s.
- Print the final matrix.



**Solution**

In [4]:


identity_5x5 = np.eye(5)
print("Initial 5x5 Identity Matrix:")
print(identity_5x5)

identity_5x5[1:4, 1:4] = 7

print("\nMatrix after replacing central 3x3 with 7s:")
print(identity_5x5)

Initial 5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Matrix after replacing central 3x3 with 7s:
[[1. 0. 0. 0. 0.]
 [0. 7. 7. 7. 0.]
 [0. 7. 7. 7. 0.]
 [0. 7. 7. 7. 0.]
 [0. 0. 0. 0. 1.]]
